site_name: Semantic Calendaring
site_url: https://www.semcal.org
theme:
  name: material
  favicon: images/favicon.png
  logo: images/semcal-logo.png
  features:
    - content.code.copy
    - navigation.tabs

repo_url: https://github.com/nodelogicau/semcal
repo_name: nodelogicau/semcal
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nodelogicau
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/benfortuna
nav:
  - Home:
    - Introduction: index.md
      - Examples:
        - Overview: examples/index.md
        - Groupware:
          - Overview: examples/groupware/index.md
          - Meeting: examples/groupware/meeting.md
          - Agenda: examples/groupware/agenda.md
          - Action: examples/groupware/action.md
          - Note: examples/groupware/note.md
          - Attendance: examples/groupware/attendance.md
          - Appointment: examples/groupware/appointment.md
        - Project Management:
          - Overview: examples/project/index.md
          - Project: examples/project/project.md
          - Objective: examples/project/objective.md
          - Milestone: examples/project/milestone.md
          - Task: examples/project/task.md
          - Risk: examples/project/risk.md
          - Issue: examples/project/issue.md
          - Decision: examples/project/decision.md
          - Timesheet: examples/project/timesheet.md
        - Agile:
          - Overview: examples/agile/index.md
          - Sprint: examples/agile/sprint.md
          - Backlog: examples/agile/backlog.md
          - Story: examples/agile/story.md
          - Epic: examples/agile/epic.md
          - Criteria: examples/agile/criteria.md
          - Retrospective: examples/agile/retrospective.md
        - Workflow:
          - Overview: examples/workflow/index.md
          - Request: examples/workflow/request.md
          - Approval: examples/workflow/approval.md
          - Roster: examples/workflow/roster.md
          - Metric: examples/workflow/metric.md
        - Catalog:
          - Overview: examples/catalog/index.md
          - Offer: examples/catalog/offer.md
          - Order: examples/catalog/order.md
          - Fulfilment: examples/catalog/fulfilment.md
        - Wiki:
          - Overview: examples/wiki/index.md
          - Article: examples/wiki/article.md
          - Topic: examples/wiki/topic.md
          - Definition: examples/wiki/definition.md
          - Faq: examples/wiki/faq.md
          
  - Rich Content: rich-content/index.md
  - Metadata:
    - Overview: metadata/index.md
    - Concepts:
        - Overview: concepts/index.md
        - Action: concepts/action.md
        - Asset: concepts/asset.md
        - Availability: concepts/availability.md
        - Event: concepts/event.md
        - Issue: concepts/issue.md
        - Metric: concepts/metric.md
        - Note: concepts/note.md
        - Observance: concepts/observance.md
        - Participant: concepts/participant.md
        - Request: concepts/request.md
  - Linking:
      - Overview: linking/index.md
      - Alternate: linking/alternate.md
      - Author: linking/author.md
      - Bookmark: linking/bookmark.md
      - Copyright: linking/copyright.md
      - Edit: linking/edit.md
      - External: linking/external.md
      - Help: linking/help.md
      - Hub: linking/hub.md
      - Icon: linking/icon.md
      - License: linking/license.md
      - Next: linking/next.md
      - Prev: linking/prev.md
      - Related: linking/related.md
      - Replies: linking/replies.md
      - Self: linking/self.md
      - Status: linking/status.md
      - Webmention: linking/webmention.md
  - Publishing:
      - Overview: publishing/index.md
      - WebSub: publishing/websub.md
      - Webmention: publishing/webmention.md

      - Budget:
          - Overview: examples/budget/index.md
          - Funding: examples/budget/funding.md
          - Expense: examples/budget/expense.md
          - Reimbursement: examples/budget/reimbursement.md
